language: c

os:
    - osx

osx_image: xcode10.2

compiler:
    - clang

addons:
    homebrew:
        packages: ncurses

install:
    - cmake -G "Unix Makefiles" .

script:
    - make all test

after_success:
    - bash <(curl -s https://codecov.io/bash)
